version: "3"
services:
  frontend:
    image: unifound-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3300

  backend:
    image: unifound-backend
    ports:
      - "3300:3300"
    depends_on:
      - mongo
    volumes:
      - uploads:/app/src/uploads
    environment:
      - MONGO_URL=mongodb://mongo:27017/unifound
      - ADMIN_TOKEN=admin
      - PORT=3300

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  uploads:
  mongodb-data:
